### ISSUE TITLE
Elección del lenguaje de programación

### ISSUE THREAD

**Issue by marinajcs** [diagmatrix/maybe-better-maybe-worse#10]
Buenas, me han asignado tu repositorio, por lo que trabajaré en el objetivo 2 sobre tu proyecto.

En primer lugar, sería conveniente llegar a un acuerdo con respecto al lenguaje de programación a utilizar.
Había pensado que TypeScript puede ser una buena elección, no solo debido a su tipado de datos, escalabilidad
y seguridad, sino también porque es muy probable que vaya a emplearse también en el proyecto "KeMeVoi".
Otras opciones serían Ruby y JavaScript.

Si prefieres usar cualquier otro, estoy abierta a sugerencias. ¿Cuál te parece más apropiado?

**Comment by diagmatrix** [comment]
Hola! Yo tenía pensado utilizar Go, pero podemos hablar para usar TypeScript.

**Comment by marinajcs** [comment]
> Hola! Yo tenía pensado utilizar Go, pero podemos hablar para usar TypeScript.

En ese caso, podemos usar Go si lo prefieres, ya que también es seguro y eficiente.
