### ISSUE TITLE
[M0-WIP] ¿Qué es un plan de rodaje?

### ISSUE THREAD

**Issue by marinajcs** [diagmatrix/maybe-better-maybe-worse#12]
Es un cronograma de producción en donde se traza una ruta de tomas/planos por grabar, dicho en otras palabras:

* Un plan de rodaje determina qué planos se van a rodar y cuándo
* Deben poder añadirse planos sobre la marcha
Contemplado en la #3

**Comment by JJ** [comment]
Todos los issues deben enlazar una historia de usuario.
