### ISSUE TITLE
[M0-WIP] ¿Qué características tiene un plano?

### ISSUE THREAD

**Issue by marinajcs** [diagmatrix/maybe-better-maybe-worse#13]
Un plan de rodaje incluye varios planos a grabar. Cada plano contiene 
los siguientes elementos:
* El tiempo estimado de grabación
* Un listado de los actores que van a participar
* El lugar y fecha donde se va a rodar
Contemplado en la #2

**Comment by JJ** [comment]
¿Qué tienen que ver los planos de rodaje con los plan*e*s de rodaje? #12
