### ISSUE TITLE
[M0-WIP] ¿Qué información se debe tener en cuenta de los actores?

### ISSUE THREAD

**Issue by marinajcs** [diagmatrix/maybe-better-maybe-worse#14]
De los actores, se debe conocer la siguiente información:
* Disponibilidad del actor
* Los planos en los que participa el actor en cuestión
Contemplado en las #2 y #5

**Comment by JJ** [comment]
Estás comentando una solución, no el problema. Si el problema es identificarlo, hay que usar solamente la información necesaria para poder hacerlo.
