### ISSUE TITLE
[M1-04] Generar objetos a partir de datos

### ISSUE THREAD

**Issue by diagmatrix** [diagmatrix/maybe-better-maybe-worse#20]
Antes de poder generar un plan de rodaje, es necesario poder crear objetos de tipo:

 - Planos
 - Actores
 - Equipo de grabación, que no se añadió al modelo de datos pero es necesario para la solución (por ejemplo, para #7 )

El equipo de grabación, puesto que suele aparecer en el plan de rodaje siempre, y necesitamos saber su disponibilidad (#7), tendrá la misma estructura que los actores, que se describe en  #14.

**Comment by JJ** [comment]
Un issue se plantea como un problema, y *nunca* incluye la solución ni la implementación, porque entonces estás convirtiendo el problema *x* (que aquí no está claro) en el *y* (leer una tabla CSV)
